### ISSUE TITLE
Errors  while running tests

### ISSUE THREAD

**Issue by Daemos87** [4lessandrodev/types-ddd#4]
Hi,

i'm trying to run tests on your repo but i get the following errors :

``` 
FAIL  tests/domain-id.spec.ts
  ● domain-id › should create a new uuid as id

    TypeError: crypto_1.randomUUID is not a function

       8 | export default class UniqueEntityID extends Identifier<string | number> {
       9 |      constructor (id?: string | number) {
    > 10 |              super(id ? id : randomUUID());
         |                              ^
      11 |      }
      12 | }
      13 |

      at new UniqueEntityID (src/core/unique-entity-id.ts:10:19)
      at Function.create (src/core/domain-id.ts:32:31)
      at Object.<anonymous> (tests/domain-id.spec.ts:10:31)

Test Suites: 5 failed, 8 passed, 13 total
```
I do not undestand what's going on, can you help me please ?

**Comment by 4lessandrodev** [comment]
Hi, @Daemos87, thanks for the report.

What is your version of the node?

This lib requires node v14.17.1 or higher.

It breaks in v12.22.1 or lower

use v14.17.1 or higher

**Comment by Daemos87** [comment]
Hi @4lessandrodev , thanks for the reply,

i was on node v14.16.1 :-)
